version: '2'
services:
    source:
        image: datasource
        container_name: source
        hostname: source
    zookeeper:
        image: zookeeper
        restart: always
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - 2181:2181
    kafka:
        image: kafka
        container_name: kafka
        hostname: kafka
        ports:
          - "9092:9092"
        depends_on:
          - zookeeper
    spark:
        image: sparktocassandra
        container_name: spark
        hostname: spark
    