    # docker-compose Cassandra Test Cluster
    # docker-compose rm
    # docker-compose up
    # docker run -it --link cassandra_cassandra-1_1:cassandra --rm cassandra cqlsh cassandra
    # copy paste the test script on cassandra-1
    # run select on cassandra-2
    #
version: '2'
services:
    cassandra-1:
      hostname: cassandra-1
      image: cassandra:latest
      command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
      expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9160
      # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
      #   - ./data/cassandra-1:/var/lib/cassandra:rw

    
